INSERT INTO Seat (id, row_no, seat_no, status, theatreid)
SELECT
    (r.row_num - 1) * 12 + s.seat_num AS id,
    r.row_num,
    s.seat_num,
    0,
    (SELECT id FROM theatre WHERE name = 'Theatre 1' LIMIT 1)
FROM
    (
    SELECT 1 row_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    ) r
    CROSS JOIN
    (
    SELECT 1 seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12
    ) s;


INSERT INTO Seat (id, row_no, seat_no, status, theatreid)
SELECT
    240 + (r.row_num - 1) * 16 + s.seat_num AS id,
    r.row_num,
    s.seat_num,
    0,
    (SELECT id FROM theatre WHERE name = 'Theatre 2' LIMIT 1)
FROM
    (
    SELECT 1 row_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
    UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
    ) r
    CROSS JOIN
    (
    SELECT 1 seat_num UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
    UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
    UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
    UNION SELECT 16
    ) s;